import React from "react"
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import './globals.css'

const _geist = Geist({ subsets: ["latin"] });
const _geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'MonitorHub | AI-Powered Website Monitoring & Uptime Tracking Platform',
  description: 'Advanced website monitoring platform with AI incident narratives, global signal mesh probes, real-time latency heatmaps, and automated incident response. Monitor uptime, performance, SSL certificates, and API endpoints with millisecond precision. Get smart alerts, AI-powered root cause analysis, and compliance-ready audit trails for production websites.',
  keywords: [
    'website monitoring',
    'uptime monitoring',
    'server monitoring',
    'API monitoring',
    'performance monitoring',
    'website health check',
    'downtime monitoring',
    'AI incident analysis',
    'latency monitoring',
    'SSL monitoring',
    'certificate monitoring',
    'real-time monitoring',
    'synthetic monitoring',
    'global monitoring',
    'multi-region monitoring',
    'incident management',
    'incident response',
    'alert management',
    'SLA monitoring',
    'website availability',
    'endpoint monitoring',
    'HTTP monitoring',
    'HTTPS monitoring',
    'website status',
    'uptime tracking',
    'performance tracking',
    'monitoring dashboard',
    'observability platform',
    'site reliability',
    'DevOps monitoring',
    'production monitoring',
    'application monitoring',
    'infrastructure monitoring',
    'cloud monitoring',
    'server uptime',
    'website speed monitoring',
    'response time monitoring',
    'ping monitoring',
    'health check monitoring',
    'status page',
    'monitoring service',
    'website analytics',
    'error tracking',
    'log monitoring',
    'metric tracking',
    'alerting system',
    'notification system',
    'incident detection',
    'anomaly detection',
    'AI monitoring',
    'machine learning monitoring',
    'automated monitoring',
    'smart alerts',
    'intelligent alerting',
    'root cause analysis',
    'performance optimization',
    'monitoring automation',
    'compliance monitoring',
    'audit trail',
    'SOC2 monitoring',
    'enterprise monitoring',
    'business monitoring',
    'e-commerce monitoring',
    'SaaS monitoring',
    'web application monitoring',
    'microservices monitoring',
    'container monitoring',
    'Kubernetes monitoring',
    'Docker monitoring',
    'serverless monitoring',
    'edge monitoring',
    'CDN monitoring',
    'DNS monitoring',
    'database monitoring',
    'API health',
    'REST API monitoring',
    'GraphQL monitoring',
    'webhook monitoring',
    'cron job monitoring',
    'scheduled task monitoring',
    'background job monitoring',
    'queue monitoring',
    'service monitoring',
    'availability monitoring',
    'reliability monitoring',
    'operational monitoring',
    'IT monitoring',
    'network monitoring',
    'connectivity monitoring',
    'probe monitoring',
    'synthetic testing',
    'smoke testing',
    'integration monitoring',
    'third-party monitoring',
    'vendor monitoring',
    'partner monitoring',
    'customer experience monitoring',
    'user monitoring',
    'session monitoring',
    'transaction monitoring',
    'checkout monitoring',
    'payment monitoring',
    'critical path monitoring',
    'business critical monitoring',
    'high availability',
    'disaster recovery',
    'failover monitoring',
    'redundancy monitoring',
    'load balancer monitoring',
    'traffic monitoring',
    'bandwidth monitoring',
    'throughput monitoring',
    'capacity monitoring',
    'resource monitoring',
    'server health',
    'application health',
    'system health',
    'infrastructure health',
    'cloud health',
    'platform health',
  ],
  authors: [{ name: 'MonitorHub' }],
  creator: 'MonitorHub',
  publisher: 'MonitorHub',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'https://monitor-hub-nine.vercel.app'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'MonitorHub | AI-Powered Website Monitoring & Uptime Tracking',
    description: 'Monitor your website uptime, performance, and API health with AI-powered incident analysis. Global signal mesh probes, real-time latency heatmaps, and smart alerts for production reliability.',
    url: process.env.NEXT_PUBLIC_APP_URL || 'https://monitor-hub-nine.vercel.app',
    siteName: 'MonitorHub',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'MonitorHub - AI Website Monitoring Platform',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'MonitorHub | AI-Powered Website Monitoring',
    description: 'Monitor uptime, performance & APIs with AI incident analysis, global probes, and real-time alerts.',
    images: ['/twitter-image.png'],
    creator: '@monitorhub',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    other: [
      {
        rel: 'android-chrome-192x192',
        url: '/android-chrome-192x192.png',
      },
      {
        rel: 'android-chrome-512x512',
        url: '/android-chrome-512x512.png',
      },
    ],
  },
  manifest: '/site.webmanifest',
  applicationName: 'MonitorHub',
  category: 'technology',
  classification: 'Website Monitoring & Performance Tools',
  other: {
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'apple-mobile-web-app-title': 'MonitorHub',
    'theme-color': '#000000',
    'msapplication-TileColor': '#000000',
    'msapplication-config': '/browserconfig.xml',
  },
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#000000' },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`font-sans antialiased`}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
